### ISSUE TITLE
点击启动之后出现如下报错：Lua Exception!

### ISSUE THREAD

**Issue by Orisn** [ping11700/LOLKit#50]
Lua Exception!
load script file failed:
F:\WeGameApps 英雄联盟 TCLS ui script init.lua

Lua Exception!
ExecuteFunction fail: CallMessageProxy not function!

**Comment by Orisn** [comment]
**在此附上我的log**

00:35:14[Info]: ************* LOLKit启动 *************
00:35:14[Info]: 自动检测到游戏路径: F:\WeGameApps\英雄联盟\TCLS\Client.exe
00:35:24[Error]-GetCs: The operation has timed out
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at KRi3PUEyXfWO6IFhXrd.O0E4mfEe2cYajRbq7CV.IYM6kIc69RZDNBIoVom8(Object , Object )
   at KRi3PUEyXfWO6IFhXrd.O0E4mfEe2cYajRbq7CV.guYEWWQ5OC(String  , Int64&  )
00:35:27[Info]: no key
00:35:37[Error]-GetCs: The operation has timed out
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at KRi3PUEyXfWO6IFhXrd.O0E4mfEe2cYajRbq7CV.IYM6kIc69RZDNBIoVom8(Object , Object )
   at KRi3PUEyXfWO6IFhXrd.O0E4mfEe2cYajRbq7CV.guYEWWQ5OC(String  , Int64&  )
00:37:11[Info]: WebSocket Close 1001
00:37:44[Error]-startReceiving: The opcode of a frame is not supported.
00:37:45[Error]-WebsocketService.SendMessage: The current state of the interface is not Open.
   at KYYbBkFwhwhkfF3BWcS.J4eB46F6ayQ1gTcBsvE.Send(String data)
   at Jk1YjGg2kZ4tfUOQ4sk.vppHu8glR3hr6iNQDgx.<<SendMessage>b__15_0>d.MoveNext()
00:37:47[Info]: WebSocket Close 1005
00:37:57[Info]: ************* LOLKit启动 *************
00:37:57[Info]: 自动检测到游戏路径: F:\WeGameApps\英雄联盟\TCLS\Client.exe
00:37:58[Info]: WebSocket Close 1001
00:37:59[Info]: no key
00:38:09[Error]-ToolClean: Access to the path 'ACE-GDPClient32.dll' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at MKWYRfGC0pfTFWX5B4yI.rU3lbSGCcDZFjmcNSc8r.v9vmlGcxDfdf0V3mbHVf(Object , Boolean )
   at MKWYRfGC0pfTFWX5B4yI.rU3lbSGCcDZFjmcNSc8r.JtrGC4Q7Jhm()
   at qfdHtGvmb2fJDkgVS2Q.bef329vaYO1yXbtCL0m.ToolClean()
00:38:13[Error]-startReceiving: The opcode of a frame is not supported.
00:38:13[Info]: WebSocket Close 1003An exception has occurred while receiving.
00:38:14[Error]-startReceiving: The header part of a frame could not be read.
00:38:16[Error]-WebsocketService.SendMessage: The current state of the interface is not Open.
   at KYYbBkFwhwhkfF3BWcS.J4eB46F6ayQ1gTcBsvE.Send(String data)
   at Jk1YjGg2kZ4tfUOQ4sk.vppHu8glR3hr6iNQDgx.<<SendMessage>b__15_0>d.MoveNext()
00:38:16[Error]-connect: No connection could be made because the target machine actively refused it 127.0.0.1:3798
00:38:18[Error]-connect: No connection could be made because the target machine actively refused it 127.0.0.1:3798
00:38:20[Error]-connect: No connection could be made because the target machine actively refused it 127.0.0.1:3798
00:38:22[Error]-connect: No connection could be made because the target machine actively refused it 127.0.0.1:3798
00:38:24[Error]-connect: No connection could be made because the target machine actively refused it 127.0.0.1:3798
00:38:26[Error]-ToolClean: Access to the path 'ACE-GDPClient32.dll' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at MKWYRfGC0pfTFWX5B4yI.rU3lbSGCcDZFjmcNSc8r.v9vmlGcxDfdf0V3mbHVf(Object , Boolean )
   at MKWYRfGC0pfTFWX5B4yI.rU3lbSGCcDZFjmcNSc8r.JtrGC4Q7Jhm()
   at qfdHtGvmb2fJDkgVS2Q.bef329vaYO1yXbtCL0m.ToolClean()
00:38:26[Error]-connect: No connection could be made because the target machine actively refused it 127.0.0.1:3798
00:38:28[Error]-connect: No connection could be made because the target machine actively refused it 127.0.0.1:3798
00:38:30[Error]-connect: No connection could be made because the target machine actively refused it 127.0.0.1:3798
00:38:32[Error]-connect: No connection could be made because the target machine actively refused it 127.0.0.1:3798
00:38:34[Error]-connect: No connection could be made because the target machine actively refused it 127.0.0.1:3798
00:38:36[Error]-connect: No connection could be made because the target machine actively refused it 127.0.0.1:3798
00:38:36[Info]: WebSocket Close 1006An exception has occurred while connecting.
00:38:36[Info]: WebSocket Close 1006An exception has occurred while connecting.
00:38:36[Info]: WebSocket Close 1006An exception has occurred while connecting.
00:38:36[Info]: WebSocket Close 1006An exception has occurred while connecting.
00:38:36[Info]: WebSocket Close 1006An exception has occurred while connecting.
00:38:36[Info]: WebSocket Close 1006An exception has occurred while connecting.
00:38:36[Info]: WebSocket Close 1006An exception has occurred while connecting.
00:38:36[Info]: WebSocket Close 1006An exception has occurred while connecting.
00:38:36[Info]: WebSocket Close 1006An exception has occurred while connecting.
00:38:36[Info]: WebSocket Close 1006An exception has occurred while connecting.
00:38:36[Info]: WebSocket Close 1006An exception has occurred while connecting.
00:38:36[Info]: WebSocket Close 1006An exception has occurred while receiving.
00:38:47[Error]-ToolClean: Access to the path 'ACE-GDPClient32.dll' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at MKWYRfGC0pfTFWX5B4yI.rU3lbSGCcDZFjmcNSc8r.v9vmlGcxDfdf0V3mbHVf(Object , Boolean )
   at MKWYRfGC0pfTFWX5B4yI.rU3lbSGCcDZFjmcNSc8r.JtrGC4Q7Jhm()
   at qfdHtGvmb2fJDkgVS2Q.bef329vaYO1yXbtCL0m.ToolClean()
00:39:03[Error]-ToolClean: Access to the path 'ACE-GDPClient32.dll' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at MKWYRfGC0pfTFWX5B4yI.rU3lbSGCcDZFjmcNSc8r.v9vmlGcxDfdf0V3mbHVf(Object , Boolean )
   at MKWYRfGC0pfTFWX5B4yI.rU3lbSGCcDZFjmcNSc8r.JtrGC4Q7Jhm()
   at qfdHtGvmb2fJDkgVS2Q.bef329vaYO1yXbtCL0m.ToolClean()
00:39:15[Error]-ToolClean: Access to the path 'ACE-GDPClient32.dll' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at MKWYRfGC0pfTFWX5B4yI.rU3lbSGCcDZFjmcNSc8r.v9vmlGcxDfdf0V3mbHVf(Object , Boolean )
   at MKWYRfGC0pfTFWX5B4yI.rU3lbSGCcDZFjmcNSc8r.JtrGC4Q7Jhm()
   at qfdHtGvmb2fJDkgVS2Q.bef329vaYO1yXbtCL0m.ToolClean()
00:39:55[Error]-ToolClean: Access to the path 'ACE-GDPClient32.dll' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at MKWYRfGC0pfTFWX5B4yI.rU3lbSGCcDZFjmcNSc8r.v9vmlGcxDfdf0V3mbHVf(Object , Boolean )
   at MKWYRfGC0pfTFWX5B4yI.rU3lbSGCcDZFjmcNSc8r.JtrGC4Q7Jhm()
   at qfdHtGvmb2fJDkgVS2Q.bef329vaYO1yXbtCL0m.ToolClean()
00:43:01[Info]: ************* LOLKit启动 *************
00:43:01[Info]: 自动检测到游戏路径: f:\wegameapps\英雄联盟\tcls\client.exe
00:43:04[Info]: no key
00:44:32[Error]-ToolClean: Access to the path 'ACE-GDPClient32.dll' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at MKWYRfGC0pfTFWX5B4yI.rU3lbSGCcDZFjmcNSc8r.v9vmlGcxDfdf0V3mbHVf(Object , Boolean )
   at MKWYRfGC0pfTFWX5B4yI.rU3lbSGCcDZFjmcNSc8r.JtrGC4Q7Jhm()
   at qfdHtGvmb2fJDkgVS2Q.bef329vaYO1yXbtCL0m.ToolClean()
00:46:12[Error]-GetCs: The operation has timed out
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at KRi3PUEyXfWO6IFhXrd.O0E4mfEe2cYajRbq7CV.IYM6kIc69RZDNBIoVom8(Object , Object )
   at KRi3PUEyXfWO6IFhXrd.O0E4mfEe2cYajRbq7CV.guYEWWQ5OC(String  , Int64&  )
00:46:45[Error]-ToolClean: Access to the path 'ACE-GDPClient32.dll' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at MKWYRfGC0pfTFWX5B4yI.rU3lbSGCcDZFjmcNSc8r.v9vmlGcxDfdf0V3mbHVf(Object , Boolean )
   at MKWYRfGC0pfTFWX5B4yI.rU3lbSGCcDZFjmcNSc8r.JtrGC4Q7Jhm()
   at qfdHtGvmb2fJDkgVS2Q.bef329vaYO1yXbtCL0m.ToolClean()
00:48:47[Info]: ************* LOLKit启动 *************
00:48:47[Info]: 自动检测到游戏路径: f:\wegameapps\英雄联盟\tcls\client.exe
00:50:09[Error]-connect: No connection could be made because the target machine actively refused it 127.0.0.1:2745
00:50:11[Error]-connect: No connection could be made because the target machine actively refused it 127.0.0.1:2745
00:50:13[Info]: WebSocket Close 1006An exception has occurred while connecting.
00:50:13[Info]: WebSocket Close 1006An exception has occurred while connecting.
00:50:13[Info]: WebSocket Close 1001
00:50:14[Error]-startReceiving: The opcode of a frame is not supported.
00:50:14[Info]: WebSocket Close 1003An exception has occurred while receiving.
00:50:16[Error]-startReceiving: The opcode of a frame is not supported.
00:50:16[Info]: WebSocket Close 1003An exception has occurred while receiving.
00:50:18[Error]-startReceiving: The opcode of a frame is not supported.
00:50:19[Info]: WebSocket Close 1003An exception has occurred while receiving.
00:50:22[Error]-startReceiving: The opcode of a frame is not supported.
00:50:22[Info]: WebSocket Close 1003An exception has occurred while receiving.
00:50:35[Error]-startReceiving: The opcode of a frame is not supported.
00:50:36[Info]: WebSocket Close 1003An exception has occurred while receiving.
01:23:11[Error]-startReceiving: The opcode of a frame is not supported.
01:23:11[Info]: WebSocket Close 1003An exception has occurred while receiving.
01:23:14[Error]-startReceiving: The opcode of a frame is not supported.
01:23:14[Info]: WebSocket Close 1003An exception has occurred while receiving.
01:23:16[Error]-startReceiving: The opcode of a frame is not supported.
01:23:17[Info]: WebSocket Close 1003An exception has occurred while receiving.
01:23:18[Error]-startReceiving: The opcode of a frame is not supported.
01:23:18[Info]: WebSocket Close 1003An exception has occurred while receiving.
01:23:39[Error]-startReceiving: The opcode of a frame is not supported.
01:23:39[Info]: WebSocket Close 1003An exception has occurred while receiving.
01:33:15[Error]-startReceiving: The opcode of a frame is not supported.
01:33:15[Info]: WebSocket Close 1003An exception has occurred while receiving.
01:33:21[Error]-startReceiving: The opcode of a frame is not supported.
01:33:21[Info]: WebSocket Close 1003An exception has occurred while receiving.
01:33:34[Error]-startReceiving: The opcode of a frame is not supported.
01:33:34[Info]: WebSocket Close 1003An exception has occurred while receiving.
02:05:06[Error]-startReceiving: The opcode of a frame is not supported.
02:05:07[Error]-WebsocketService.SendMessage: The current state of the interface is not Open.
   at KYYbBkFwhwhkfF3BWcS.J4eB46F6ayQ1gTcBsvE.Send(String data)
   at Jk1YjGg2kZ4tfUOQ4sk.vppHu8glR3hr6iNQDgx.<<SendMessage>b__15_0>d.MoveNext()
02:05:09[Info]: WebSocket Close 1005

**Comment by ping11700** [comment]
lolclient bug
