### ISSUE TITLE
The WebSocket protocol is not supported on this platform.【windows7】

### ISSUE THREAD

**Issue by nosiyBUGS** [ping11700/LOLkit#93]
23:33:24[Info]: ************* LOLKit启动 v2.4.5 *************
23:33:24[Fatal]-APP.Fatal: The WebSocket protocol is not supported on this platform.
   at System.Net.WebSockets.WebSocketHelpers.ThrowPlatformNotSupportedException_WSPC()
   at System.Net.WebSockets.ClientWebSocket..ctor()
   at o9RUe58aMJm8pbWaJhE.urU0xy80kORFQAYloiU..ctor()
   at ochlrD82A10rpTyWdN5.v9Kjo88LhcTvaphvWkS.Kvh8oxEMVr()
   at gA5MXuo1jITSdBvW0h.kindoW2pSqI5Cyu6jj.kNgOIl1TViNn6sxJkkAD(Object )
   at gA5MXuo1jITSdBvW0h.kindoW2pSqI5Cyu6jj.OnStartup(StartupEventArgs  )
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ping11700** [comment]
已更换websocket
